plugins {
    id 'java'
}

group = 'org.sahariardev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation group: 'io.netty', name: 'netty-all', version: '4.1.119.Final'
}

test {
    useJUnitPlatform()
}